import pandas as pd
df = pd.read_csv("student_skill_assessment.csv")
print(df.head())
print(df.shape)
print(df.columns)
print(df.isnull().sum())
df["Communication"] = df["Communication"].fillna(df["Communication"].mean())
df["Leadership"] = df["Leadership"].fillna(df["Leadership"].mean())
df["Presentation"] = df["Presentation"].fillna(df["Presentation"].mean())
print(df.isnull().sum())
print(df["Python"].mean())
print(df[["Python", "Problem_Solving", "Communication", "Teamwork", "Leadership", "Creativity", "Time_Management", "Presentation"]].mean())
print(df["Overall_Score"].mean())
print(df["Overall_Score"].max())
print(df["Overall_Score"].min())
print(df.groupby("Department")["Overall_Score"].mean())
print(df["Department"].value_counts())
print(df["Skill_Level"].value_counts())
print(df.groupby("Skill_Level")["Overall_Score"].mean())
print(df[["Student_Name", "Department", "Overall_Score", "Skill_Level"]].sort_values("Overall_Score", ascending=False).head(10))
print(df[["Student_Name", "Department", "Overall_Score", "Skill_Level"]].sort_values("Overall_Score", ascending=False).head(10).to_string(index=False))
print(df.groupby("Year")["Overall_Score"].mean())
print(df.groupby("Gender")["Overall_Score"].mean())
print(df[["Python", "Problem_Solving", "Communication", "Teamwork", "Leadership", "Creativity", "Time_Management", "Presentation"]].mean().sort_values(ascending=False))
print(df.groupby("Department")["Overall_Score"].mean().sort_values(ascending=False))
print(df.groupby("Year")["Overall_Score"].mean())
print(df.groupby("Gender")["Overall_Score"].mean())
print(df[df["Student_Name"] == "Aditi Joshi"][["Student_Name", "Department", "Year", "Overall_Score", "Skill_Level"]])
import matplotlib.pyplot as plt
df.groupby("Department")["Overall_Score"].mean().plot(kind="bar", title="Average Overall Score by Department")
plt.show()
plt.xlabel("Department")
plt.ylabel("Average Overall Score")
df.groupby("Skill_Level")["Overall_Score"].count().plot(kind="pie", autopct="%1.1f%%", title="Skill Level Distribution")
plt.show()
df["Overall_Score"].plot(kind="hist", bins=10, title="Distribution of Overall Scores")
plt.show()
df.nlargest(10, "Overall_Score").plot(x="Student_Name", y="Overall_Score", kind="bar", title="Top 10 Students by Overall Score", legend=False)
plt.show()
print("Weakest Skill:", df[["Python", "Problem_Solving", "Communication", "Teamwork", "Leadership", "Creativity", "Time_Management", "Presentation"]].mean().idxmin())
print("Strongest Skill:", df[["Python", "Problem_Solving", "Communication", "Teamwork", "Leadership", "Creativity", "Time_Management", "Presentation"]].mean().idxmax())
print("Skill Gap:", df[["Python", "Problem_Solving", "Communication", "Teamwork", "Leadership", "Creativity", "Time_Management", "Presentation"]].mean().max() - df[["Python", "Problem_Solving", "Communication", "Teamwork", "Leadership", "Creativity", "Time_Management", "Presentation"]].mean().min())
print("Recommendation: Focus on improving Presentation skills.")
print("Best Department:", df.groupby("Department")["Overall_Score"].mean().idxmax())
print("Needs Improvement Department:", df.groupby("Department")["Overall_Score"].mean().idxmin())
print("Department Performance Gap:", df.groupby("Department")["Overall_Score"].mean().max() - df.groupby("Department")["Overall_Score"].mean().min())
print("Total Students:", df["Student_ID"].nunique())
print("Advanced Students:", (df["Skill_Level"] == "Advanced").sum())
print("Intermediate Students:", (df["Skill_Level"] == "Intermediate").sum())
print("Beginner Students:", (df["Skill_Level"] == "Beginner").sum())
print("Advanced Percentage:", (df["Skill_Level"] == "Advanced").mean() * 100)
print("Intermediate Percentage:", (df["Skill_Level"] == "Intermediate").mean() * 100)
print("Beginner Percentage:", (df["Skill_Level"] == "Beginner").mean() * 100)
print("Median Overall Score:", df["Overall_Score"].median())
print("Overall Score Std Dev:", df["Overall_Score"].std())
print("Top Student:", df.loc[df["Overall_Score"].idxmax(), "Student_Name"])
print("Top Student Score:", df["Overall_Score"].max())
print("Top Student Department:", df.loc[df["Overall_Score"].idxmax(), "Department"])
print("Top Student Skill Level:", df.loc[df["Overall_Score"].idxmax(), "Skill_Level"])
print("Students in CSE:", (df["Department"] == "CSE").sum())
print("CSE Average Score:", df[df["Department"] == "CSE"]["Overall_Score"].mean())
print("Lowest Department:", df.groupby("Department")["Overall_Score"].mean().idxmin())
print("Civil Average Score:", df[df["Department"] == "Civil"]["Overall_Score"].mean())
print("Overall Median Score:", df["Overall_Score"].median())
print("Score Standard Deviation:", df["Overall_Score"].std())
print("Year 4 Average Score:", df[df["Year"] == 4]["Overall_Score"].mean())
print("Female Average Score:", df[df["Gender"] == "Female"]["Overall_Score"].mean())
print("Male Average Score:", df[df["Gender"] == "Male"]["Overall_Score"].mean())
print("Strongest Skill:", df[["Python", "Problem_Solving", "Communication", "Teamwork", "Leadership", "Creativity", "Time_Management", "Presentation"]].mean().idxmax())
print("Weakest Skill:", df[["Python", "Problem_Solving", "Communication", "Teamwork", "Leadership", "Creativity", "Time_Management", "Presentation"]].mean().idxmin())
print("Skill Gap:", df[["Python", "Problem_Solving", "Communication", "Teamwork", "Leadership", "Creativity", "Time_Management", "Presentation"]].mean().max() - df[["Python", "Problem_Solving", "Communication", "Teamwork", "Leadership", "Creativity", "Time_Management", "Presentation"]].mean().min())
print("Best Department:", df.groupby("Department")["Overall_Score"].mean().idxmax())
print("Advanced Percentage:", (df["Skill_Level"] == "Advanced").mean() * 100)
print("Intermediate Percentage:", (df["Skill_Level"] == "Intermediate").mean() * 100)
print("Beginner Percentage:", (df["Skill_Level"] == "Beginner").mean() * 100)
print(df.groupby("Department")[["Python", "Problem_Solving", "Communication", "Teamwork", "Leadership", "Creativity", "Time_Management", "Presentation"]].mean().round(2))
print(df.groupby("Year")[["Python", "Problem_Solving", "Communication", "Teamwork", "Leadership", "Creativity", "Time_Management", "Presentation"]].mean().round(2))
print(df.groupby("Gender")[["Python", "Problem_Solving", "Communication", "Teamwork", "Leadership", "Creativity", "Time_Management", "Presentation"]].mean().round(2))
print(df[df["Student_Name"] == "Aditi Joshi"][["Student_Name", "Python", "Problem_Solving", "Communication", "Teamwork", "Leadership", "Creativity", "Time_Management", "Presentation"]].to_string(index=False))
print("Aditi Weakest Skill:", df[df["Student_Name"] == "Aditi Joshi"][["Python", "Problem_Solving", "Communication", "Teamwork", "Leadership", "Creativity", "Time_Management", "Presentation"]].mean().idxmin())
print("Aditi Skill Gap:", df[df["Student_Name"] == "Aditi Joshi"][["Python", "Problem_Solving", "Communication", "Teamwork", "Leadership", "Creativity", "Time_Management", "Presentation"]].max(axis=1).iloc[0] - df[df["Student_Name"] == "Aditi Joshi"][["Python", "Problem_Solving", "Communication", "Teamwork", "Leadership", "Creativity", "Time_Management", "Presentation"]].min(axis=1).iloc[0])
print("Aditi Strongest Skill:", df[df["Student_Name"] == "Aditi Joshi"][["Python", "Problem_Solving", "Communication", "Teamwork", "Leadership", "Creativity", "Time_Management", "Presentation"]].mean().idxmax())
print("Aditi Recommendation: Focus on improving Leadership skills.")
print("Student Search Ready:", df["Student_Name"].nunique(), "unique students available")
print("Largest Department:", df["Department"].value_counts().idxmax(), "-", df["Department"].value_counts().max(), "students")
print("Smallest Department:", df["Department"].value_counts().idxmin(), "-", df["Department"].value_counts().min(), "students")
print("Skill Correlation Matrix:\n", df[["Python", "Problem_Solving", "Communication", "Teamwork", "Leadership", "Creativity", "Time_Management", "Presentation"]].corr().round(2))
print("Strongest Skill Relationship:", df[["Python", "Problem_Solving", "Communication", "Teamwork", "Leadership", "Creativity", "Time_Management", "Presentation"]].corr().where(lambda x: x < 1).stack().idxmax())
print("Strongest Correlation Value:", df["Problem_Solving"].corr(df["Teamwork"]).round(2))
print("Correlation Insight: Problem Solving and Teamwork show a moderate positive relationship (0.49).")
print("Assessment Period:", df["Assessment_Date"].min(), "to", df["Assessment_Date"].max())
print("Assessments by Month:", pd.to_datetime(df["Assessment_Date"]).dt.month.value_counts().sort_index().to_dict())
print("Busiest Assessment Month:", pd.to_datetime(df["Assessment_Date"]).dt.month.value_counts().idxmax())
print("Duplicate Rows:", df.duplicated().sum())
print("Unique Student IDs:", df["Student_ID"].nunique())
print("Student ID Integrity:", "Valid" if df["Student_ID"].nunique() == len(df) else "Duplicate IDs Found")
print("Data Quality Status:", "Excellent" if df.isnull().sum().sum() == 0 and df.duplicated().sum() == 0 and df["Student_ID"].nunique() == len(df) else "Needs Review")
print("Overall Score Range:", round(df["Overall_Score"].max() - df["Overall_Score"].min(), 2))
print("Monthly Average Scores:", df.assign(Month=pd.to_datetime(df["Assessment_Date"]).dt.month).groupby("Month")["Overall_Score"].mean().round(2).to_dict())
print("Best Assessment Month:", pd.to_datetime(df["Assessment_Date"]).dt.month.groupby(pd.to_datetime(df["Assessment_Date"]).dt.month).apply(lambda x: df.loc[x.index, "Overall_Score"].mean()).idxmax())
print("Lowest Assessment Month:", pd.to_datetime(df["Assessment_Date"]).dt.month.groupby(pd.to_datetime(df["Assessment_Date"]).dt.month).apply(lambda x: df.loc[x.index, "Overall_Score"].mean()).idxmin())

print("Highest Scoring Year:", df.groupby("Year")["Overall_Score"].mean().idxmax())

print("Lowest Scoring Year:", df.groupby("Year")["Overall_Score"].mean().idxmin())

print("Highest Scoring Gender:", df.groupby("Gender")["Overall_Score"].mean().idxmax())

print("Lowest Scoring Gender:", df.groupby("Gender")["Overall_Score"].mean().idxmin())

print("Highest Skill Average:", round(df[["Python", "Problem_Solving", "Communication", "Teamwork", "Leadership", "Creativity", "Time_Management", "Presentation"]].mean().max(), 2))

print("Lowest Skill Average:", round(df[["Python", "Problem_Solving", "Communication", "Teamwork", "Leadership", "Creativity", "Time_Management", "Presentation"]].mean().min(), 2))